Fallback version when not specified

diff --git a/detect b/detect
--- a/detect
+++ b/detect
@@ -1,8 +1,10 @@
 #!/bin/sh -l
 set -eu
-[ ! -f "$1" ] && echo "global.json does not exist at $1"
-[ ! -f "$1" ] && exit 1
-VERSION=$(sed -n 's|.*"version":\s*"\([^"]*\)".*|\1|p' "$1")
+
+VERSION="${2-}"
+[ -f "$1" ] && VERSION=$(sed -n 's|.*"version":\s*"\([^"]*\)".*|\1|p' "$1")
+
+[ -z "$VERSION" ] && echo "Version not found" && exit 1
 
 echo ".NET Version: $VERSION"
 echo "DOTNET_VERSION=$VERSION" >> $GITHUB_ENV
